# Generated by Django 2.1.1 on 2018-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_cents', models.IntegerField()),
                ('rating', models.FloatField()),
                ('volume_discount_percent', models.IntegerField()),
                ('volume_discount_threshold', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
