# Generated by Django 2.1.1 on 2018-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_discount_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_discount_threshold',
            field=models.IntegerField(null=True),
        ),
    ]
